name: 'Gary Collier : My Life'
favicon: null
layout_spectrum: 0.9980272923130542
typography_spectrum: 0.37318958551622927
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b6d7e6'
    - '#628285'
    - '#050508'
    - '#005e99'
  brandStrength: 0.5
  lightness: 0.4744924930855632
  saturation: 0.5
  rhythmicContrast: 0.744828736409545
purpose: []
